name: campusstylistflutter
description: A Flutter app for Campus Stylist.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  dio: ^5.7.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  table_calendar: ^3.0.9
  test: ^1.24.0
  mockito: ^5.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13 # Updated to latest compatible version
  json_serializable: ^6.8.0
  mockito: ^5.4.6 # Already correct, kept as is

flutter:
  uses-material-design: true