// // Mocks generated by Mockito 5.4.6 from annotations
// // in campusstylistflutter/test/mocks.dart.
// // Do not manually edit this file.
//
// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i8;
//
// import 'package:campusstylistflutter/models/auth_request.dart' as _i10;
// import 'package:campusstylistflutter/models/auth_response.dart' as _i2;
// import 'package:campusstylistflutter/models/booking.dart' as _i5;
// import 'package:campusstylistflutter/models/create_profile_response.dart'
//     as _i4;
// import 'package:campusstylistflutter/models/login_request.dart' as _i9;
// import 'package:campusstylistflutter/models/post.dart' as _i11;
// import 'package:campusstylistflutter/models/user.dart' as _i6;
// import 'package:campusstylistflutter/models/user_profile.dart' as _i3;
// import 'package:campusstylistflutter/services/api_service.dart' as _i7;
// import 'package:mockito/mockito.dart' as _i1;
// import 'package:mockito/src/dummies.dart' as _i12;
//
// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: must_be_immutable
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class
//
// class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
//   _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }
//
// class _FakeUserProfile_1 extends _i1.SmartFake implements _i3.UserProfile {
//   _FakeUserProfile_1(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }
//
// class _FakeCreateProfileResponse_2 extends _i1.SmartFake
//     implements _i4.CreateProfileResponse {
//   _FakeCreateProfileResponse_2(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }
//
// class _FakeBooking_3 extends _i1.SmartFake implements _i5.Booking {
//   _FakeBooking_3(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }
//
// class _FakeUser_4 extends _i1.SmartFake implements _i6.User {
//   _FakeUser_4(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }
//
// /// A class which mocks [ApiService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockApiService extends _i1.Mock implements _i7.ApiService {
//   MockApiService() {
//     _i1.throwOnMissingStub(this);
//   }
//
//   @override
//   _i8.Future<_i2.AuthResponse> login(_i9.LoginRequest? request) =>
//       (super.noSuchMethod(
//             Invocation.method(#login, [request]),
//             returnValue: _i8.Future<_i2.AuthResponse>.value(
//               _FakeAuthResponse_0(this, Invocation.method(#login, [request])),
//             ),
//           )
//           as _i8.Future<_i2.AuthResponse>);
//
//   @override
//   _i8.Future<_i2.AuthResponse> signUp(_i10.AuthRequest? request) =>
//       (super.noSuchMethod(
//             Invocation.method(#signUp, [request]),
//             returnValue: _i8.Future<_i2.AuthResponse>.value(
//               _FakeAuthResponse_0(this, Invocation.method(#signUp, [request])),
//             ),
//           )
//           as _i8.Future<_i2.AuthResponse>);
//
//   @override
//   _i8.Future<_i3.UserProfile> getUserProfile(String? token) =>
//       (super.noSuchMethod(
//             Invocation.method(#getUserProfile, [token]),
//             returnValue: _i8.Future<_i3.UserProfile>.value(
//               _FakeUserProfile_1(
//                 this,
//                 Invocation.method(#getUserProfile, [token]),
//               ),
//             ),
//           )
//           as _i8.Future<_i3.UserProfile>);
//
//   @override
//   _i8.Future<_i4.CreateProfileResponse> createProfile({
//     required String? username,
//     required String? bio,
//     String? profilePicturePath,
//     required String? token,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#createProfile, [], {
//               #username: username,
//               #bio: bio,
//               #profilePicturePath: profilePicturePath,
//               #token: token,
//             }),
//             returnValue: _i8.Future<_i4.CreateProfileResponse>.value(
//               _FakeCreateProfileResponse_2(
//                 this,
//                 Invocation.method(#createProfile, [], {
//                   #username: username,
//                   #bio: bio,
//                   #profilePicturePath: profilePicturePath,
//                   #token: token,
//                 }),
//               ),
//             ),
//           )
//           as _i8.Future<_i4.CreateProfileResponse>);
//
//   @override
//   _i8.Future<_i5.Booking> createBooking(_i5.Booking? booking) =>
//       (super.noSuchMethod(
//             Invocation.method(#createBooking, [booking]),
//             returnValue: _i8.Future<_i5.Booking>.value(
//               _FakeBooking_3(
//                 this,
//                 Invocation.method(#createBooking, [booking]),
//               ),
//             ),
//           )
//           as _i8.Future<_i5.Booking>);
//
//   @override
//   _i8.Future<List<_i5.Booking>> getBookingsByHairstylistDate(
//     int? hairstylistId,
//     String? date,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#getBookingsByHairstylistDate, [
//               hairstylistId,
//               date,
//             ]),
//             returnValue: _i8.Future<List<_i5.Booking>>.value(<_i5.Booking>[]),
//           )
//           as _i8.Future<List<_i5.Booking>>);
//
//   @override
//   _i8.Future<List<_i11.Post>> getPostsByHairdresserId(
//     String? hairdresserId,
//     String? token,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#getPostsByHairdresserId, [hairdresserId, token]),
//             returnValue: _i8.Future<List<_i11.Post>>.value(<_i11.Post>[]),
//           )
//           as _i8.Future<List<_i11.Post>>);
//
//   @override
//   _i8.Future<String> fetchHairdresserId(String? token) =>
//       (super.noSuchMethod(
//             Invocation.method(#fetchHairdresserId, [token]),
//             returnValue: _i8.Future<String>.value(
//               _i12.dummyValue<String>(
//                 this,
//                 Invocation.method(#fetchHairdresserId, [token]),
//               ),
//             ),
//           )
//           as _i8.Future<String>);
//
//   @override
//   _i8.Future<List<_i11.Post>> getAllPosts(String? token) =>
//       (super.noSuchMethod(
//             Invocation.method(#getAllPosts, [token]),
//             returnValue: _i8.Future<List<_i11.Post>>.value(<_i11.Post>[]),
//           )
//           as _i8.Future<List<_i11.Post>>);
//
//   @override
//   _i8.Future<_i6.User> getUserById(String? id, String? token) =>
//       (super.noSuchMethod(
//             Invocation.method(#getUserById, [id, token]),
//             returnValue: _i8.Future<_i6.User>.value(
//               _FakeUser_4(this, Invocation.method(#getUserById, [id, token])),
//             ),
//           )
//           as _i8.Future<_i6.User>);
//
//   @override
//   _i8.Future<void> logout(String? token) =>
//       (super.noSuchMethod(
//             Invocation.method(#logout, [token]),
//             returnValue: _i8.Future<void>.value(),
//             returnValueForMissingStub: _i8.Future<void>.value(),
//           )
//           as _i8.Future<void>);
// }
